# Generated by Co-Pilot GPT 4
# Difficulty added by 19009152

import random
'''
update:
added an option for user to select a difficulty 
easy - shows hints
normal - basic game as it was - vanilla
hard - imposed a guess limit
'''
def guess_the_number():
    print("Welcome to 'Guess the Number'!")
    difficulty_options = [1,2,3]
    while True:
        try:
            difficulty = int(input("Please select difficulty\n  1. Easy - Show Hints\n  2. Normal - No Hints, No Guess Limit\n  3. Hard - No Hints, Max 10 Guesses"))
            if difficulty not in difficulty_options:
                print('Select from the choices')
            else:
                print(f'user selected level {difficulty}')
                break
        except ValueError:
            ("Please Enter a Number: 1, 2, or 3")

    number_to_guess = random.randint(1, 100)
    attempts = 0
    max_attempts = 10

    while True:
        try:
            guess = int(input("Enter your guess (1-100): "))
            attempts += 1
            if difficulty == 3 and attempts == max_attempts:
                print(f' Sorry! You have failed to guess the number after {max_attempts}')
                break

            if guess < 1 or guess > 100:
                print("Please guess a number between 1 and 100.")
            elif guess < number_to_guess:
                if difficulty == 1:
                    if number_to_guess - guess <= 5:
                        print('Hint: Really Warm')
                    elif number_to_guess - guess >= 10:
                        print('Hint: A Bit Cold')
                    else: print ('Hint: A Bit Warm')
                print("Too low! Try again.")
            elif guess > number_to_guess:
                if difficulty == 1:
                    if guess - number_to_guess <= 5:
                        print('Hint: Really Warm')
                    elif guess - number_to_guess >= 10:
                        print('Hint: A Bit Cold')
                    else: print ('Hint: A Bit Warm')
                print("Too high! Try again.")
            else:
                print(f"Congratulations! You guessed the number in {attempts} attempts.")
                break
        except ValueError:
            print("Invalid input. Please enter a number.")

guess_the_number()